<?xml version="1.0" encoding="utf-8"?><Database Name="WHPE_db" Class="DBConnectionDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\WHPE_db.mdf;Integrated Security=True" SettingsObjectName="WHeditor.Properties.Settings" SettingsPropertyName="WHPE_dbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Rase" Member="Rases">
    <Type Name="Rase">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RaseName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RaseDescription" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>